# Contains 2496 rare english words and 1000 commonly used enlgish words
word_list = [
    "abaft", "abalienate", "abalone", "abaptiston", "abarticulation", "abasia", "abaxial", "abbatial",
    "abdominous", "abecedarian", "aberuncate", "abessive", "abeyant", "abgregate", "abhorson", "abience",
    "abiogenesis", "abiotic", "abjuration", "ablactation", "ablation", "ablative", "ablepsia", "abligurition",
    "abnegate", "abodement", "abolition", "aboral", "abortifacient", "aboulia", "abrasax", "abreaction",
    "abscission", "abstemious", "abstersion", "abstruse", "acalculia", "acanthous", "acarpous", "acatalepsy",
    "acaulescent", "accidence", "accidie", "acclimate", "accolade", "accretion", "acculturate", "acephalia",
    "acerbate", "acervate", "acetabulum", "acicular", "acinaceous", "aciniform", "acinus", "aclastic",
    "acmatic", "acmesthesia", "acnodal", "acosmism", "acotyledon", "acouasm", "acousma", "acrasia",
    "acrimony", "acrocephalic", "acromegaly", "acromial", "acrophony", "acrospire", "acroter", "actinism",
    "actinomycosis", "actuarially", "acuity", "acuminate", "adactylous", "adamantine", "adapid", "adaxial",
    "addorsed", "adducent", "adelaster", "ademption", "adenopathy", "adespota", "adiabatic", "adipocere",
    "adiaphorous", "adnate", "adnominal", "adscititious", "adumbrate", "adventitious", "adversaria", "aecium",
    "aerenchyma", "aerolite", "aeromancy", "aerophagy", "aesthesia", "aetiology", "affinal", "agamic",
    "agamogenesis", "agastric", "agentive", "agerasia", "agglomerate", "agglutinative", "agnoiology", "agonic",
    "agonistic", "agrestic", "agrimensor", "agrostology", "aguish", "aidant", "aiglet", "ailurophile",
    "aiphyllous", "aischrolatreia", "aitchbone", "ajutage", "akrasia", "alalia", "aleatoric", "alembic",
    "alexia", "algesia", "algesic", "algolagnia", "alimentation", "aliquot", "allodium", "allopathy",
    "allophane", "allophonic", "alluvion", "almucantar", "alnage", "alodium", "altricial", "alveolar",
    "ambagious", "ambitty", "amblygon", "amboceptor", "ambsace", "ameliorate", "amenorrhea", "amerce",
    "ammonite", "amnion", "amniotic", "amorce", "amphiarthrosis", "amphigory", "amphimixis", "amphiprostyle",
    "ampullaceous", "amygdaloid", "anabiosis", "anabolic", "anachron", "anacrusis", "anadiplosis", "anaerobic",
    "anagnorisis", "analecta", "analgesic", "anaphylaxis", "anastomosis", "anatropous", "anchorite", "anciform",
    "anfractuous", "anhedonia", "anhydrous", "anile", "anisogamy", "ankylosis", "annomination", "annular",
    "anodyne", "anomia", "anopheles", "antepenult", "anthelmintic", "antheridium", "anthropomorphic", "antibrachial",
    "anticline", "antinomian", "antinomic", "antinomy", "antiphrasis", "antipodal", "antiphon", "antistrophe",
    "antithesis", "antonomasia", "anuresis", "aoristic", "apanthropy", "apastron", "aphanite", "aphasia",
    "aphelion", "apheresis", "aphonia", "aphorism", "apiary", "apocarp", "apocarpy", "apocope",
    "apodeictic", "apodictic", "apophasis", "apophony", "apophthegm", "apoplexy", "aposiopesis", "apostrophe",
    "apothegm", "apotropaic", "appanage", "aquiline", "arcanist", "areology", "argot", "ariel",
    "armigerous", "arrogation", "asperse", "asperity", "asphyxiation", "asseverate", "astragal", "atavistic",
    "ataxia", "atony", "atrabilious", "atrophic", "attenuate", "autarky", "autochthonous", "automaton",
    "autotelic", "auxesis", "avulsion", "axiological", "axonometric", "azimuth", "azoic", "azoth",
    "bacchanalia", "badinage", "bailiwick", "balbucinate", "ballistic", "bardolatry", "basal", "bathetic",
    "bathos", "bathymetry", "bathyscaph", "batrachian", "beadledom", "bedizen", "benighted", "benthos",
    "bibliomancy", "bibliophile", "bibliopole", "biopsy", "bipartite", "blandishment", "blastocoele", "blepharon",
    "borborygmus", "boskiness", "botulism", "brachycephalic", "brachylogy", "brackish", "bradycardia", "bravura",
    "brecciated", "brimstone", "brumous", "buccal", "bucolic", "cacoethes", "cacophony", "cadastral",
    "cadaverous", "cadential", "caducity", "caducous", "caesura", "calcareous", "calumniate", "camarilla",
    "canorous", "capacious", "capillary", "captious", "carcinogenic", "carditis", "caries", "carnassial",
    "carpophore", "cartilaginous", "caseharden", "caseous", "catalectic", "catalepsy", "catallactics", "catarrhine",
    "cathexis", "cauda", "caudate", "caudex", "caulescent", "cedilla", "celibacy", "cenotaph",
    "cephalic", "cephalopod", "ceraceous", "cerement", "chalcedony", "chiasmus", "chiliasm", "chirography",
    "chitinous", "chitin", "chordal", "choriamb", "cicatrix", "cinereous", "circadian", "cismontane",
    "clastic", "clavicular", "climacteric", "clonus", "coagulate", "coaptation", "codicil", "colophon",
    "comeuppance", "comminatory", "comminute", "commutative", "conation", "concupiscence", "condign", "coniine",
    "connatural", "consanguine", "constuprate", "contumely", "convolution", "cordate", "corticate", "cotyledon",
    "cozenage", "crapulous", "crimination", "crochet", "culpable", "cuneate", "cunctation", "cupellation",
    "cynosure", "dactylic", "dactylology", "daedal", "daphnia", "debridement", "decalescence", "decumbent",
    "defeasible", "defalcation", "deipnosophist", "deictic", "deliquescent", "demesne", "demiurge", "demotic",
    "deontology", "dernier", "desiderium", "desiccate", "desultory", "diapason", "diaphoresis", "diaspore",
    "diastema", "diathesis", "dichotomous", "dicrotic", "diegetic", "diglossic", "digraphic", "dimorphic",
    "dipsomania", "discalceate", "disquisition", "distrait", "diuretic", "divagate", "docimasy", "dolorous",
    "donjon", "dubitant", "durance", "dynamometry", "dysarthria", "dyspepsia", "ebullition", "eccentric",
    "ecdysis", "ecocline", "edenate", "egregious", "eidetic", "eidos", "ekphrasis", "elide",
    "elision", "embouchure", "embrocation", "emendation", "empyrean", "enarration", "endemic", "endoplasm",
    "enervate", "entelechy", "ependyma", "epexegesis", "epicritic", "epicycle", "epidictic", "epilemma",
    "epinosic", "epistrophe", "epitaxy", "epithelium", "equinoctial", "eremite", "ergograph", "eroteme",
    "eructation", "erumpent", "escarpment", "esoteric", "estival", "etiolate", "eudaemonic", "euhemerism",
    "eutrophy", "exanthema", "excogitate", "excoriate", "exegesis", "exogamy", "exophthalmic", "expiate",
    "expunge", "exsanguinate", "extrapolate", "exuviate", "facetious", "falcate", "feculent", "feoffment",
    "feral", "ferrule", "fervid", "fistulous", "flocculent", "florilegium", "fluvial", "foment",
    "footpad", "forcible", "forensic", "forfend", "formication", "frangible", "frenulum", "friable",
    "frowsty", "fugacious", "fulgurate", "fulminate", "fulvous", "fumarole", "funerary", "furfuraceous",
    "galvanic", "gamboge", "gangrene", "garrulous", "genuflect", "geomorphic", "gerundive", "gnomic",
    "gonophore", "gracile", "gramineous", "granuloma", "gravid", "gregarious", "grume", "gyrate",
    "habituation", "hamartia", "haptic", "haplography", "haptotropism", "haversack", "hebdomad", "hebephrenia",
    "hebetude", "heliograph", "hemoptysis", "herpetic", "heuristic", "hierarchical", "hirsute", "histology",
    "homeostasis", "homiletics", "homoeopath", "homogeneous", "homomorphic", "hyaline", "hydrolysis", "hypertrophy",
    "hysteresis", "ichneumon", "ichnography", "ichor", "icterus", "idiopathic", "idiosyncrasy", "igneous",
    "ignominy", "imbroglio", "immolate", "immutable", "impecunious", "impedimenta", "impetigo", "imprimatur",
    "imputative", "inchoate", "incubus", "inculpate", "induration", "ineludible", "infarction", "infrangible",
    "ingenue", "insouciant", "intromission", "inveterate", "involution", "ipsedixitism", "irredentism", "isogon",
    "isomorphic", "iterative", "jejune", "juxtapose", "karyotype", "kenosis", "ketosis", "kymograph",
    "lacrimose", "lagniappe", "laical", "laminar", "lapidary", "latent", "latitudinarian", "lenticular",
    "leptosome", "lesion", "lethean", "leucorrhea", "lexical", "ligature", "limpid", "lithography",
    "litigious", "lixiviate", "logicism", "logodaedaly", "logomachy", "lordosis", "lucubration", "lugubrous",
    "macerate", "maladroit", "malefic", "malversation", "manifold", "mansard", "marginal", "meningeal",
    "meniscus", "mercurial", "meristematic", "mesenchyme", "metastable", "metempsychosis", "micturition", "miosis",
    "mnemonic", "modality", "morphosis", "mucilaginous", "mutism", "myopia", "nacreous", "naevus",
    "narcissism", "narcosis", "noctiluca", "nodular", "nomenklatura", "normative", "nosology", "nostalgia",
    "noxious", "oblation", "obnubilate", "obsequious", "obstreperous", "occipital", "oligophrenia", "ominous",
    "omission", "omophagia", "oneiromancy", "onomastics", "ontogenesis", "onychomancy", "opacity", "opprobrious",
    "organogenesis", "ornithomancy", "ossification", "osteomyelitis", "ostracism", "otiose", "outlandish", "palinode",
    "palimpsest", "palliation", "panegyric", "parabole", "parabolic", "paresthesia", "paretic", "pariah",
    "parietal", "patulous", "pedunculate", "pejorative", "pellucid", "penultimate", "penurious", "pericardium",
    "perigee", "peripatetic", "peristalsis", "peroration", "pestiferous", "petulant", "philomath", "phlebitis",
    "phlegmatic", "phospholipid", "phrenic", "phytotoxin", "picayune", "pileous", "pinguitude", "plangent",
    "plenum", "plethoric", "pleuritic", "podagra", "pollination", "polygenism", "polymorphous", "pontifical",
    "postulate", "pragmatic", "praxis", "predatory", "preponderance", "prescient", "prevaricate", "priapism",
    "prolepsis", "propinquity", "proscenium", "prosopagnosia", "protean", "purulent", "quiescent", "rapacious",
    "recidivism", "recondite", "rectitude", "refractory", "remonstrate", "renegade", "reprobate", "resurgent",
    "retribution", "rheology", "rhetorical", "rimose", "riparian", "risible", "sacerdotal", "salubrious",
    "sanguine", "sclerosis", "scoliosis", "semiotic", "senescence", "sequester", "serration", "sibilant",
    "sidereal", "solipsism", "somatic", "somatotype", "soporific", "specious", "spoliation", "spurious",
    "steatorrhea", "stenosis", "stipulate", "stolid", "subcutaneous", "subliminal", "subterfuge", "supine",
    "suppurate", "sycophantic", "synapse", "synaptic", "syncope", "syncretic", "tabescent", "tachycardia",
    "tautology", "teleological", "teratology", "testicular", "thermolysis", "thrombosis", "torsion", "toxicosis",
    "troglodyte", "turbulent", "ululation", "umbilical", "unctuous", "undulant", "unguent", "uniparous",
    "vagarious", "vapid", "variegated", "veneration", "vertiginous", "vestigial", "vicarious", "virulence",
    "visceral", "vituperate", "vociferous", "volitional", "vomition", "xenoglossia", "xeric", "zymotic",
    "abaxile", "abcoulomb", "abdominoscopy", "abecedary", "abenteric", "aberrative", "abhorrent", "abiogenetic",
    "ablutomania", "abmortal", "abnormality", "abomination", "aborning", "abortive", "abortogenic", "absinthiated",
    "absolution", "absorptive", "abstraction", "acanthocyte", "acaulous", "accipitrine", "acclive", "acclivous",
    "acetous", "achromic", "acidulous", "aciform", "aclinic", "acosmist", "acoustical", "acquiescent",
    "acranial", "adeniform", "adenoid", "adessive", "adipsia", "adnation", "adventive", "advolution",
    "aequorin", "aeriform", "aerogel", "aestival", "afebrile", "afferent", "affiant", "afflatus",
    "afforce", "aftmost", "agamous", "agitato", "agnomen", "agonism", "agraphia", "agrestal",
    "aguelike", "aileron", "aimbolic", "alactation", "alertness", "algesimeter", "algogenic", "aliased",
    "alimentary", "allopatric", "altercate", "altruism", "aluminous", "ambiguous", "amortize", "amplexus",
    "ampullary", "anabolism", "anaclitic", "anaemia", "anaerobe", "anafrotous", "analectic", "analogue",
    "anamnesis", "anapestical", "anaplasia", "anaphase", "anarchism", "anechoic", "anergia", "aneurismal",
    "angioedema", "anisocytosis", "annulment", "anosmia", "antagonistic", "anthesis", "anthropic", "antiperistalsis",
    "antithetic", "aortic", "aphasic", "aplastic", "apogeal", "apomixis", "apostate", "appetence",
    "appoggiatura", "apterous", "aqueous", "arachnoid", "arboreal", "archetypical", "architectonic", "areolate",
    "arithmetical", "aromatic", "arpeggio", "arrythmia", "arteriole", "arthrosis", "asbestiform", "aseptic",
    "asphyxial", "aspirate", "assimilation", "astatic", "asterism", "atactic", "atheistic", "atlantal",
    "atrabilian", "attrition", "auditory", "autistic", "autochthon", "autogamy", "autologous", "autonomic",
    "autonymous", "autosome", "autotomy", "avascular", "aventurine", "axillary", "azimuthal", "bacillary",
    "bacteremia", "bacteriostatic", "balanitis", "barometric", "bartholinitis", "barypathia", "basophilic", "bathonian",
    "benthic", "biconvex", "bifurcate", "bilious", "bilobular", "bioptic", "biphasic", "bivalent",
    "blastomere", "blepharitis", "borborygmic", "bradykinesia", "brachiation", "bromidrosis", "bronchiole", "bronchitis",
    "bursitis", "cacosmia", "caducean", "calcarenite", "callous", "calycinal", "canalicular", "cancellous",
    "capitate", "capsomere", "carotenoid", "caruncle", "catoptric", "caustic", "cephalalgic", "cerebration",
    "chaotic", "chatoyant", "chiasmatic", "choanal", "cholemic", "cholinergic", "chondral", "chromatin",
    "chromatogram", "cicatricial", "ciliary", "cinctured", "cirrhotic", "clitellate", "cloakal", "clubbable",
    "coeliac", "cogitative", "commensal", "comminution", "concessive", "congenital", "conjugation", "consolatory",
    "contralateral", "cordiform", "corollary", "corporeal", "corrugation", "corticospinal", "costive", "craniometric",
    "crepitant", "crescent", "cretinism", "cryptogamic", "crystallography", "cuticular", "cyanosis", "cyclothymia",
    "cystitis", "dacryocyst", "dactylitis", "degeneracy", "dementive", "dermal", "dermoid", "deteriorate",
    "detrusor", "diapedesis", "diastolic", "diencephalon", "dimorphism", "dioptric", "diplegic", "disseminate",
    "diurnal", "diverticulum", "dolichocephalic", "doliform", "dorsiflex", "drusenhead", "dyschromatism", "dysgraphia",
    "dysphoria", "dysphasia", "dystrophic", "ectoderm", "ectogenic", "edematous", "efferent", "efflorescence",
    "egotistical", "electrolysis", "elephantine", "ellipsoid", "emaciation", "embryonic", "encephalitis", "endocardium",
    "endocrine", "endogamy", "endogenous", "endometrium", "endophyte", "endoplasmic", "eosinophilic", "epidermoid",
    "epigenesis", "epilemmal", "epinephrine", "epistemic", "epitympanic", "equilateral", "erythema", "esophageal",
    "estrogen", "etiological", "eugenics", "euthyroid", "exocrine", "exophthalmos", "extensor", "extrapolation",
    "exudative", "fasciation", "fasciculus", "febrile", "fibrinous", "fibromyalgia", "filiform", "flagellate",
    "flexor", "floriation", "fluviatile", "follicular", "formative", "foveate", "fusiform", "ganglion",
    "gastric", "germinal", "glabellar", "glandular", "glenoid", "glomerulus", "glycolysis", "gnathic",
    "gonadotropic", "granulomatous", "granulocyte", "gyrencephalic", "hallucination", "haematoma", "haemorrhagic", "hemodynamic",
    "hepatic", "hermeneutic", "histrionic", "homeomorphic", "homozygous", "humoral", "hyperplasia", "hypnagogic",
    "hypoglycemia", "hypostasis", "hypothalamic", "ichthyic", "iliac", "immunogenic", "impetuous", "incubate",
    "induction", "infundibulum", "inhibitory", "intracellular", "ischemia", "isometric", "jejunal", "kaleidoscopic",
    "keratotic", "kinesthetic", "lamellar", "laryngeal", "lentigo", "leptocephalic", "lesional", "lobular",
    "lumbosacral", "lymphadenopathy", "macrophage", "meningitis", "metabolic", "metaplasia", "microbic", "mitotic",
    "monocular", "morbific", "mucosal", "myalgic", "myasthenic", "myeloma", "myofibril", "narcotic",
    "necrotic", "neonatal", "nephron", "neurasthenic", "neurotrophic", "nodose", "nomenclatural", "nucleic",
    "obesity", "occluded", "odontoid", "oliguria", "olfactory", "opacification", "osmotic", "ovarian",
    "oviparous", "oxidative", "palpation", "pancreatic", "papillary", "parenteral", "parous", "pathogenic",
    "pectoral", "peptidase", "perinatal", "peripheral", "phagocytic", "pharyngeal", "phonemic", "phyletic",
    "phytogenic", "pilosebaceous", "pineal", "pituitary", "placental", "plantar", "pneumatic", "podiatric",
    "polycythemia", "polymeric", "polyphasic", "postural", "proliferative", "proteolytic", "proximal", "psoriatic",
    "pulmonary", "pyloric", "radicular", "reactive", "recessive", "regenerative", "renal", "retinal",
    "retrobulbar", "rheumatic", "sacular", "sagittal", "sarcolemma", "sclerotic", "secretory", "seminal",
    "serological", "sinusoidal", "spermatogonia", "spinal", "steroidal", "stromal", "subacute", "sympathetic",
    "synovial", "systolic", "thalamic", "thoracic", "thrombotic", "thyroidal", "tidal", "trabecular",
    "transcription", "transduction", "trigeminal", "trophic", "urinary", "uterine", "vascular", "ventricular",
    "vitreous", "vocal", "zygomatic", "zymogenic", "ablactose", "abscessional", "accentual", "achromatic",
    "acrodont", "acromion", "actomyosin", "adenocarcinoma", "adipogenic", "adrenocortical", "allosteric", "altruistic",
    "amylolytic", "anhydrosis", "anisotropic", "ankylosing", "antecubital", "antibody", "anticoagulant", "antimetabolite",
    "antiphlogistic", "apocrine", "apoptosis", "argyria", "articular", "aspartate", "atelectasis", "atherosclerosis",
    "audiometric", "bimanual", "bioavailability", "blennorrhea", "bolometric", "brachial", "bronchoalveolar", "buccinator",
    "bulbospinal", "caecal", "calvarial", "carboxylation", "carcinomatous", "cardiovascular", "caudothalamic", "cellularity",
    "centromeric", "cerebellar", "cervicodorsal", "chemoreceptor", "chiromancy", "chlorophyll", "chronometric", "cingulate",
    "coagulopathy", "coloboma", "colorectal", "commissural", "condyloid", "conjunctival", "contractility", "costovertebral",
    "craniofacial", "craniotomy", "cribriform", "cruciate", "cytoplasmic", "defibrillation", "degenerative", "dendritic",
    "denticulate", "dermoscopy", "desmosome", "diaphragmatic", "diffusion", "diplopia", "discogenic", "dissection",
    "dorsolateral", "ductal", "echocardiographic", "ectopic", "elastomeric", "electrolytic", "embryogenesis", "emphysematous",
    "endodermal", "endothelial", "enterocyte", "enzymatic", "eosinophilia", "epididymal", "epistaxis", "erythrocyte",
    "fascicular", "femoral", "fibrillation", "fibrocytic", "gastroesophageal", "germline", "glomerulonephritis", "glycosylation",
    "gonadal", "granulocytic", "hamstring", "hemolytic", "hepatocellular", "hilar", "hormonal", "hydrocephalus",
    "hypercoagulation", "hyperemia", "hyperosmolar", "hypopituitarism", "idiosyncratic", "immunosuppressive", "incisional", "infrapatellar",
    "intercostal", "interstitial", "intracranial", "intrathecal", "intrinsic", "ipsilateral", "ischial", "isotonic",
    "keratinous", "lacunar", "lateral", "leukopoiesis", "lipophilic", "lithotomy", "lumbar", "lymphocytic",
    "macrocytic", "malignant", "mandibular", "medullary", "mesenteric", "microvascular", "migratory", "mononuclear",
    "myocardial", "neoplastic", "neurogenic", "neurolysis", "nociceptive", "normocytic", "nucleocytoplasmic", "obturator",
    "oligodendrocyte", "oncolytic", "ophthalmopathy", "osteoporosis", "oxidoreductase", "parasagittal", "pathognomonic", "peribronchial",
    "periodontal", "peritoneal", "peroxisomal", "phosphorylation", "plexopathy", "pneumococcal", "pontine", "prepubescent",
    "prostate", "proteomics", "pruriginous", "pseudomembranous", "ptotic", "radiographic", "reticuloendothelial", "retroperitoneal",
    "rhizotomy", "rostral", "sacropelvic", "sarcomere", "scaphoid", "septicemia", "sigmoid", "spermatozoa",
    "splenic", "stenotic", "suboccipital", "substernal", "supraclavicular", "sympathomimetic", "tachypnea", "tendinous",
    "thyrotoxic", "tracheotomy", "transfusion", "triglyceride", "tubulointerstitial", "ulcerative", "urethral", "uveal",
    "valvular", "vasomotor", "venoplasty", "vestibular", "viscosity", "xanthoma", "xerostomia", "xiphoid",
    "zeroth", "zymolysis", "abiogenous", "ablastin", "abrasion", "absorbate", "acanthoma", "acetolysis",
    "achlorhydria", "achromotrichia", "acneiform", "acousia", "acoustics", "actionable", "adductor", "adenolipoma",
    "adsorption", "adrenocorticotropic", "aerobics", "aflatoxin", "agammaglobulinemia", "agenesis", "aldosterone", "allergenicity",
    "allograft", "alopecianism", "ameloblast", "ammonemia", "amyloidosis", "androgen", "aneurysmal", "angiofibroma",
    "angiogenesis", "angiomatous", "anorectal", "anosognosia", "antibiotic", "antidiuretic", "antineoplastic", "antinuclear",
    "antioxidant", "antipyretic", "aortocoronary", "aponeurosis", "apoptotic", "arboviruses", "arrhythmia", "arteriosclerosis",
    "arthropathy", "aspergillosis", "astrocyte", "ataxic", "atrophy", "autoantibody", "autograft", "axonotmesis",
    "bacteriuria", "basocellular", "bathochromic", "biochemistry", "bioinformatics", "biomarker", "blastogenesis", "blepharospasm",
    "bradyphrenia", "bronchospasm", "bursal", "calcination", "calculus", "carcinogenesis", "cardiomegaly", "catecholamine",
    "catheterization", "cerebrovascular", "chemokine", "cholestasis", "cholinesterase", "clonazepam", "coagulation", "cochlear",
    "collagenase", "confabulatory", "congestive", "contracture", "corticotropin", "crepitation", "cysticercosis", "cytochromes",
    "debilitation", "decongestant", "delirium", "dementia", "demyelination", "densitometry", "dermatitis", "desensitization",
    "diagnosis", "dilatation", "dissemination", "dopaminergic", "dyslipidemia", "dysrhythmia", "echoencephalography", "ectomorphic",
    "elastase", "electrolyte", "embolism", "encephalopathy", "endocarditis", "endomyocarditis", "enteropathy", "epidemiology",
    "epileptiform", "erythropoiesis", "exocytosis", "exuberant", "fasciotomy", "fibroblast", "fibrosis", "fracture",
    "gangliopathy", "gastroenterology", "glioblastoma", "glomerular", "glycerophospholipid", "hematopoiesis", "hemostasis", "hepatopathy",
    "histamine", "hyperthyroidism", "hypoalbuminemia", "hypothermia", "immunofluorescence", "immunomodulatory", "impairment", "inflammation",
    "integument", "interleukin", "intraoperative", "ischemic", "ketogenesis", "laminectomy", "laparoscopy", "leukopenia",
    "lipogenesis", "lipolysis", "lymphangioma", "lymphopenia", "malabsorption", "mammography", "mediastinum", "melancholy",
    "metastasis", "methemoglobin", "microbiome", "mitochondria", "monoplegia", "mucinous", "multiple", "mutation",
    "necrosis", "neonatology", "nephropathy", "neurotransmitter", "nociception", "normoglycemia", "oropharyngeal", "orthopedic",
    "osteogenesis", "ovulatory", "pancytopenia", "parenthetical", "perineum", "perivascular", "phlebothrombosis", "physiopathology",
    "plasmapheresis", "polydipsia", "polyuria", "postoperative", "prognosis", "proliferation", "prophylaxis", "psychiatry",
    "ptosis", "pulmonology", "radiotherapy", "recurrence", "regeneration", "remission", "reperfusion", "respiration",
    "restoration", "resuscitation", "rhabdomyolysis", "rupture", "sarcopenia", "sclerotherapy", "serotonin", "sigmoidoscopy",
    "somatization", "steatosis", "sympatholytic", "syndromic", "tachyphylaxis", "tenotomy", "thrombocytopenia", "thyrotoxicosis",
    "tonsillitis", "toxicology", "transaminase", "treatment", "tricuspid", "tumor", "ulceration", "urticaria",
    "uveitis", "vasculitis", "virology", "voluminous", "xerophthalmia", "zoonosis", "abecedarium", "ablaut",
    "acatamathesia", "acataleptic", "acathexia", "accismus", "acoloutha", "acolouthic", "acrotism", "acyrologia",
    "adynaton", "aetiological", "agathism", "agnosia", "agrapha", "alexithymia", "alieniloquy", "allochiria",
    "alloeosis", "allonomous", "amphimacer", "anacoenosis", "anacoluthon", "analemma", "analogism", "anamnetic",
    "anaphoric", "anastrophe", "anatreptic", "ancilla", "anesis", "animadversion", "anomism", "antanaclasis",
    "antapodosis", "antepenultimate", "anthorism", "anthypophora", "antilogy", "antiparastasis", "antiptosis", "antistasis",
    "antitheton", "antonomastic", "apagogical", "aphoristic", "apomnemonysis", "apoplanesis", "aposiopetic", "apostrophal",
    "apriorism", "arenaceous", "argufication", "arithmomania", "asyndeton", "atavism", "atrabiliar", "atrichorism",
    "atrocity", "autexousia", "autological", "auxological", "axiomatics", "battology", "bdelygmia", "cacozelia",
    "catachresis", "cataphatic", "cataphora", "cataphoric", "cataplasis", "catastasis", "catastrophe", "catchphrasis",
    "catechistical", "catechumen", "categorematic", "cautelous", "centonism", "chrematomancy", "chronomancy", "clarissimat",
    "cleptomania", "cogitabund", "colometry", "commoratio", "concessio", "contentio", "convicium", "correctio",
    "dehortation", "deiosis", "delectus", "deontological", "deprecatio", "diatyposis", "dicaeologia", "dichotomy",
    "digressio", "dinumeratio", "distinctio", "distributio", "dubitatio", "ecphrasis", "elenctic", "ellipsis",
    "enantiosis", "enthymematic", "epanalepsis", "epanorthosis", "epexegetical", "epitrope", "equivocation", "erotesis",
    "ethopoeia", "eulogia", "exergasia", "exordium", "expeditio", "foreshadowing", "gnomological", "gradatio",
    "hermeneutical", "holism", "homiletical", "hyperbaton", "hyperbolic", "hypophora", "hypozeugma", "hysterology",
    "illeism", "implicature", "innutrition", "interlocution", "isocolon", "laconic", "liotes", "litotes",
    "logorrheic", "metalepsis", "metaplasm", "metataxis", "mimesis", "mythopoeia", "noetic", "nominalism",
    "nomology", "noospheric", "occultism", "onomatology", "optative", "oratorical", "ostensible", "oxymoron",
    "paradiastole", "paraenesis", "paragoge", "paralipsis", "paroemia", "paroemiology", "paromoiosis", "paronomasia",
    "parrhesia", "pathopoeia", "peristasis", "phantasmal", "pleonasm", "polyptoton", "polysyndeton", "pragmatics",
    "procatalepsis", "proleptic", "proslepsis", "protrope", "psephology", "pseudepigrapha", "psithurism", "ratiocinative",
    "reductionism", "semiology", "sophrosyne", "synchysis", "synecdochic", "synoeciosis", "tautegory", "theosophy",
    "topothesia", "triacal", "tyromancy", "unitarianism", "universalism", "utilitarianism", "verbalism", "vexillology",
    "viridescence", "vitalism", "voluntarism", "zeugmatic", "zoanthropy", "abaton", "abirritate", "abjure",
    "acephalous", "acervative", "acescent", "acetarious", "achroous", "acnode", "acolyte", "acquest",
    "acrimoniousness", "adamancy", "adeism", "adipescent", "adoxography", "adroit", "adscript", "adulation",
    "aduncous", "aglet", "agnize", "ailurophobia", "algedonic", "algophobia", "alienation", "allotheism",
    "allocatur", "allodial", "allonym", "altiloquence", "altruist", "alveolate", "amatorial", "amaurosis",
    "ambagitory", "ambivalence", "amortization", "amphibology", "amphitheater", "anarchic", "anchoretic", "ancientrye",
    "annalistic", "anterograde", "antiquary", "apodal", "appurtenance", "arcuate", "areopagite", "argentiferous",
    "argyronomy", "aristocratic", "armigeral", "arrestment", "artless", "ascendancy", "aseverate", "assiduity",
    "assurgent", "attaint", "attritive", "auctoritas", "augment", "auspicate", "autocephalous", "averment",
    "baldric", "balistae", "ballaster", "banshee", "barathrum", "barbican", "bardic", "bastinado",
    "bawd", "behoof", "beholden", "bellicosity", "belomancy", "bemixt", "benefice", "bespeak",
    "bibliolatry", "bifarious", "biliousness", "blackguard", "blandish", "blatherskite", "blench", "borborygm",
    "boskage", "bowdlerize", "braggadocio", "bromide", "brumal", "bryology", "bumptious", "caitiff",
    "callidity", "callosity", "calumny", "captivate", "capybara", "caricature", "carking", "carnality",
    "causerie", "caveat", "cenacle", "censure", "centurion", "circumlocution", "clamancy", "claustral",
    "claviger", "cloister", "cognoscible", "commination", "comport", "comstockery", "contumelious", "coprolalia",
    "cordial", "countenance", "cupidity", "dastardly", "dauphin", "deadfall", "declension", "decorticate",
    "defalcate", "defamation", "demurrage", "denizen", "descry", "dissimulation", "doughty", "doxy",
    "draconian", "dulcet", "dystopia", "efface", "effrontery", "embellish", "eminence", "emolument",
    "empanelment", "enounce", "ensorcell", "enumeration", "equipoise", "equivocate", "errant", "escutcheon",
    "exculpate", "exigent", "expeditious", "fain", "fatuous", "fealty", "fecundity", "felony",
    "fiat", "fiduciary", "flout", "forbearance", "foreswear", "forfeit", "forthright", "fractious",
    "froward", "gallimaufry", "gastronomy", "gauntlet", "germane", "glibness", "gnarly", "grandiloquence",
    "gratuitous", "guile", "halcyon", "harangue", "harbinger", "haughtiness", "hegemony", "heinous",
    "heretical", "heterodox", "huckster", "iconoclast", "idiomatic", "ignominious", "illocutionary", "impassioned",
    "impugn", "inanity", "inchoateness", "incipient", "inconsistency", "indolence", "iniquity", "injudicious",
    "insipid", "insouciance", "insufferable", "insular", "intemperance", "interdict", "inure", "invective",
    "irascible", "jocose", "lachrymose", "lambent", "languor", "larceny", "lassitude", "laudation",
    "lenient", "libertine", "licentious", "loquacious", "lugubrious", "magnanimous", "malediction", "malfeasance",
    "mendacious", "mendicant", "mercenary", "meretricious", "moiety", "munificent", "nabob", "naïveté",
    "negligence", "nepotism", "nescience", "noblesse", "nominal", "nonchalance", "nugatory", "obdurate",
    "obloquy", "odious", "opprobrium", "oscillation", "ostentation", "otiosity", "outrage", "overweening",
    "palaver", "panache", "parsimonious", "paucity", "peevish", "penchant", "perfidious", "periphrasis",
    "persiflage", "pertinacity", "perverse", "pettifogging", "phlegm", "picaresque", "pinchbeck", "placard",
    "pleonastic", "plutocrat", "poltroon", "pomposity", "pragmatism", "precipitate", "precocious", "predilection",
    "pretentious", "priggish", "prodigal", "profane", "profligate", "prolix", "promiscuous", "propagandist",
    "pulchritude", "punctilious", "pusillanimous", "quibble", "querulous", "rancorous", "raucous", "recreant",
    "redolent", "reprehensible", "reticent", "rife", "rodomontade", "sardonic", "scurrilous", "sententious",
    "servile", "sibilance", "simony", "sloth", "solecism", "somnolent", "spendthrift", "splenetic",
    "squalid", "squander", "supercilious", "superfluous", "surreptitious", "sycophancy", "taciturn", "tenacious",
    "tergiversation", "timorous", "transgressive", "truculent", "tumultuous", "turgid", "turpitude", "umbrage",
    "unscrupulous", "uxorious", "vacuous", "vagary", "venal", "verbose", "vilify", "vocation",
    "wanton", "wayward", "weal", "wily", "winsome", "abditive", "abirritation", "absinthism",
    "acaudate", "accubation", "acerose", "acetabular", "acholia", "achromatopsia", "acidimetry", "acousticophobia",
    "acroanesthesia", "actinic", "acupressure", "adactylia", "adenitis", "adenomyosis", "adrenalectomy", "adrenergic",
    "adsorptive", "aeroembolism", "aesthesiometer", "agalactia", "agrypnia", "akathisia", "akinesis", "alastrim",
    "aldosteronism", "alexithymics", "algometer", "alloplasty", "alopecia", "alveolitis", "amelogenesis", "aminoaciduria",
    "amusia", "anarthria", "anencephaly", "aneuploid", "angiitis", "anorgasmia", "anosmiac", "anoxemia",
    "antalgic", "anthracosis", "antidromic", "antisepsis", "antrectomy", "aphthous", "apophysis", "apraxia",
    "aptyalism", "arteritis", "arthralgia", "asthenia", "astigmatism", "ateleiosis", "atheromatous", "atresia",
    "atrioventricular", "audiogram", "autolysis", "autopoiesis", "azotemia", "bacteriophage", "balneology", "baroreceptor",
    "bibliotherapy", "bilharziasis", "biosynthesis", "blastoderm", "blepharoconjunctivitis", "bordetella", "bradylalia", "brucellosis",
    "byssinosis", "cachexia", "capnography", "carbuncle", "carcinosis", "cardiomyopathy", "catabolism", "catatonia",
    "cellulosic", "cephalalgia", "cerclage", "cheiromegaly", "chemotaxis", "cholangitis", "chorionic", "chromesthesia",
    "chromhidrosis", "chronobiology", "coagulase", "condyloma", "coprolagnia", "cordocentesis", "corticofugal", "craurosis",
    "creatinuria", "cryptorchidism", "curettage", "cystocele", "debility", "decompensation", "defervescence", "deoxygenation",
    "depilation", "dermatophyte", "deuteranopia", "dextrocardia", "diaschisis", "dichromia", "diplegia", "disarticulation",
    "dolorimetry", "duodenitis", "dyshidrosis", "dyskinesia", "dyslexia", "dysmenorrhea", "dysmorphia", "ecchymosis",
    "echolalia", "eclampsia", "ectropion", "edentulous", "electromyogram", "embolectomy", "enanthema", "encephalocele",
    "enterobiasis", "epiphysis", "ergonomics", "erotomania", "erysipelas", "excitability", "exfoliation", "fasciitis",
    "febricity", "fenestration", "festination", "fibromata", "fistulography", "galactorrhea", "galactosemia", "gangliosidosis",
    "gastrectomy", "gastroschisis", "gingivitis", "glaucoma", "granulomatosis", "graphospasm", "gynecomastia", "hallux",
    "hamartoma", "hematemesis", "hemianopsia", "hemochromatosis", "hepatomegaly", "heterochromia", "hidradenitis", "hydrarthrosis",
    "hyperalgesia", "hyperesthesia", "hypertrichosis", "hypogonadism", "hypospadia", "hypotonia", "iatrogenic", "ileostomy",
    "impetigenous", "incontinence", "intussusception", "iridocyclitis", "isocoria", "keratoconus", "kinesiology", "kleptomania",
    "lacunarity", "laparectomy", "laryngoscopy", "leucocytosis", "lithiasis", "lymphangiectasis", "lymphocytosis", "macroglobulinemia",
    "maculopathy", "malacia", "mastodynia", "mastoiditis", "megacolon", "melanoma", "menarche", "meningioma",
    "mesothelium", "micrognathia", "micrographia", "monocytosis", "morbidity", "morphometry", "mucormycosis", "myasthenia",
    "mycosis", "myelitis", "myelofibrosis", "myoclonus", "myokymia", "myomectomy", "myopathy", "myositis",
    "narcolepsy", "nasolacrimal", "natriuresis", "necrotizing", "nephritis", "neuropathy", "neutropenia", "nodulosis",
    "nystagmus", "odontogenic", "oligodendroglioma", "oncocyte", "ophthalmoplegia", "orchidopexy", "osteoclasis", "osteolysis",
    "osteophyte", "otosclerosis", "oxytocic", "pachydermia", "palatoplasty", "paleoanthropology", "panniculitis", "papilledema",
    "paragonimiasis", "paraurethral", "parotitis", "patellofemoral", "pediculosis", "pellagra", "pemphigus", "penectomy",
    "perforation", "pericarditis", "periosteitis", "pharyngitis", "phenylketonuria", "pheochromocytoma", "phimosis", "phlebography",
    "phlebotomy", "photodermatitis", "photophobia", "phytopathology", "pityriasis", "pleurisy", "pneumoconiosis", "podocyte",
    "polydactyly", "polyhydramnios", "polyneuritis", "polypharmacy", "porencephaly", "postphlebitic", "preeclampsia", "presbycusis",
    "presbyopia", "proctitis", "prostatism", "proteinuria", "pseudarthrosis", "pseudocyesis", "psychomotor", "puberty",
    "pyelogram", "pyoderma", "pyonephrosis", "pyrexia", "applepie", "able", "about", "above", "accept", "according", "account", "across", "act", "action", 
    "activity", "actually", "add", "address", "administration", "admit", "adult", "affect", "after", "again", 
    "against", "age", "agency", "agent", "ago", "agree", "agreement", "ahead", "air", "all", 
    "allow", "almost", "alone", "along", "already", "also", "although", "always", "American", "among", 
    "amount", "analysis", "and", "animal", "another", "answer", "any", "anyone", "anything", "appear", 
    "apply", "approach", "area", "argue", "arm", "around", "arrive", "art", "article", "artist", 
    "as", "ask", "assume", "at", "attack", "attention", "attorney", "audience", "author", "authority", 
    "available", "avoid", "away", "baby", "back", "bad", "bag", "ball", "bank", "bar", 
    "base", "be", "beat", "beautiful", "because", "become", "bed", "before", "begin", "behavior", 
    "behind", "believe", "benefit", "best", "better", "between", "beyond", "big", "bill", "billion", 
    "bit", "black", "blood", "blue", "board", "body", "book", "born", "both", "box", 
    "boy", "break", "bring", "brother", "budget", "build", "building", "business", "but", "buy", 
    "by", "call", "camera", "campaign", "can", "cancer", "candidate", "capital", "car", "card", 
    "care", "career", "carry", "case", "catch", "cause", "cell", "center", "central", "century", 
    "certain", "certainly", "chair", "challenge", "chance", "change", "character", "charge", "check", "child", 
    "choice", "choose", "church", "citizen", "city", "civil", "claim", "class", "clear", "clearly", 
    "close", "coach", "cold", "collection", "college", "color", "come", "commercial", "common", "community", 
    "company", "compare", "computer", "concern", "condition", "conference", "Congress", "consider", "consumer", "contain", 
    "continue", "control", "cost", "could", "country", "couple", "course", "court", "cover", "create", 
    "crime", "cultural", "culture", "cup", "current", "customer", "cut", "dark", "data", "daughter", 
    "day", "dead", "deal", "death", "debate", "decade", "decide", "decision", "deep", "defense", 
    "degree", "Democrat", "democratic", "describe", "design", "despite", "detail", "determine", "develop", "development", 
    "die", "difference", "different", "difficult", "direction", "director", "discover", "discuss", "discussion", "disease", 
    "do", "doctor", "dog", "door", "down", "draw", "dream", "drive", "drop", "drug", 
    "during", "each", "early", "east", "easy", "eat", "economic", "economy", "edge", "education", 
    "effect", "effort", "eight", "either", "election", "else", "employee", "end", "energy", "enjoy", 
    "enough", "enter", "entire", "environment", "environmental", "especially", "establish", "even", "evening", "event", 
    "ever", "every", "everybody", "everyone", "everything", "evidence", "exactly", "example", "executive", "exist", 
    "expect", "experience", "expert", "explain", "eye", "face", "fact", "factor", "fail", "fall", 
    "family", "far", "fast", "father", "fear", "federal", "feel", "feeling", "few", "field", 
    "fight", "figure", "fill", "film", "final", "finally", "financial", "find", "fine", "finger", 
    "finish", "fire", "firm", "first", "fish", "five", "floor", "fly", "focus", "follow", 
    "food", "foot", "for", "force", "foreign", "forget", "form", "former", "forward", "four", 
    "free", "friend", "from", "front", "full", "fund", "future", "game", "garden", "gas", 
    "general", "generation", "get", "girl", "give", "glass", "go", "goal", "good", "government", 
    "great", "green", "ground", "group", "grow", "growth", "guess", "gun", "guy", "hair", 
    "half", "hand", "hang", "happen", "happy", "hard", "have", "he", "head", "health", 
    "hear", "heart", "heat", "heavy", "help", "her", "here", "herself", "high", "him", 
    "himself", "his", "history", "hit", "hold", "home", "hope", "hospital", "hot", "hotel", 
    "hour", "house", "how", "however", "huge", "human", "hundred", "husband", "I", "idea", 
    "identify", "if", "image", "imagine", "impact", "important", "improve", "in", "include", "including", 
    "increase", "indeed", "indicate", "individual", "industry", "information", "inside", "instead", "institution", "interest", 
    "interesting", "international", "interview", "into", "investment", "involve", "issue", "it", "item", "its", 
    "itself", "job", "join", "just", "keep", "key", "kid", "kill", "kind", "kitchen", 
    "know", "knowledge", "land", "language", "large", "last", "late", "later", "laugh", "law", 
    "lawyer", "lay", "lead", "leader", "learn", "least", "leave", "left", "leg", "legal", 
    "less", "let", "letter", "level", "lie", "life", "light", "like", "likely", "line", 
    "list", "listen", "little", "live", "local", "long", "look", "lose", "loss", "lot", 
    "love", "low", "machine", "magazine", "main", "maintain", "major", "majority", "make", "man", 
    "manage", "management", "manager", "many", "market", "marriage", "material", "matter", "may", "maybe", 
    "me", "mean", "measure", "media", "medical", "meet", "meeting", "member", "memory", "mention", 
    "message", "method", "middle", "might", "military", "million", "mind", "minute", "miss", "mission", 
    "model", "modern", "moment", "money", "month", "more", "morning", "most", "mother", "mouth", 
    "move", "movement", "movie", "Mr", "Mrs", "much", "music", "must", "my", "myself", 
    "name", "nation", "national", "natural", "nature", "near", "nearly", "necessary", "need", "network", 
    "never", "new", "news", "newspaper", "next", "nice", "night", "no", "none", "nor", 
    "north", "not", "note", "nothing", "notice", "now", "number", "occur", "off", "offer", 
    "office", "officer", "official", "often", "oh", "oil", "ok", "old", "on", "once", 
    "one", "only", "onto", "open", "operation", "opportunity", "option", "or", "order", "organization", 
    "other", "others", "our", "out", "outside", "over", "own", "owner", "page", "pain", 
    "painting", "paper", "parent", "part", "participant", "particular", "particularly", "partner", "party", "pass", 
    "past", "patient", "pattern", "pay", "peace", "people", "per", "perform", "performance", "perhaps", 
    "period", "person", "personal", "phone", "physical", "pick", "picture", "piece", "place", "plan", 
    "plant", "play", "player", "PM", "point", "police", "policy", "political", "politics", "poor", 
    "popular", "population", "position", "positive", "possible", "power", "practice", "prepare", "present", "president", 
    "pressure", "pretty", "prevent", "price", "private", "probably", "problem", "process", "produce", "product", 
    "production", "professional", "professor", "program", "project", "property", "protect", "prove", "provide", "public", 
    "pull", "purpose", "push", "put", "quality", "question", "quickly", "quite", "race", "radio", 
    "raise", "range", "rate", "rather", "reach", "read", "ready", "real", "reality", "realize", 
    "really", "reason", "receive", "recent", "recently", "recognize", "record", "red", "reduce", "reflect", 
    "region", "relate", "relationship", "religious", "remain", "remember", "remove", "report", "represent", "Republican", 
    "require", "research", "resource", "respond", "response", "responsibility", "rest", "result", "return", "reveal", 
    "rich", "right", "rise", "risk", "road", "rock", "role", "room", "rule", "run", 
    "safe", "same", "save", "say", "scene", "school", "science", "scientist", "score", "sea", 
    "season", "seat", "second", "section", "security", "see", "seek", "seem", "sell", "send", 
    "senior", "sense", "series", "serious", "serve", "service", "set", "seven", "several", "sex", 
    "sexual", "shake", "share", "she", "shoot", "short", "shot", "should", "shoulder", "show", 
    "side", "sign", "significant", "similar", "simple", "simply", "since", "sing", "single", "sister", 
    "sit", "site", "situation", "six", "size", "skill", "skin", "small", "smile", "so", 
    "social", "society", "soldier", "some", "somebody", "someone", "something", "sometimes", "son", "song", 
    "soon", "sort", "sound", "source", "south", "southern", "space", "speak", "special", "specific", 
    "speech", "spend", "sport", "spring", "staff", "stage", "stand", "standard", "star", "start", 
    "state", "statement", "station", "stay", "step", "still", "stock", "stop", "store", "story", 
    "strategy", "street", "strong", "structure", "student", "study", "stuff", "style", "subject", "success", 
    "successful", "such", "suddenly", "suffer", "suggest", "summer", "support", "sure", "surface", "system", 
    "table", "take", "talk", "task", "tax", "teach", "teacher", "team", "technology", "television", 
    "tell", "ten", "tend", "term", "test", "than", "thank", "that", "the", "their", 
    "them", "themselves", "then", "theory", "there", "these", "they", "thing", "think", "third", 
    "this", "those", "though", "thought", "thousand", "threat", "three", "through", "throughout", "throw", 
    "thus", "time", "to", "today", "together", "tonight", "too", "top", "total", "tough", 
    "toward", "town", "trade", "traditional", "training", "travel", "treat", "treatment", "tree", "trial", 
    "trip", "trouble", "true", "truth", "try", "turn", "TV", "two", "type", "under", 
    "understand", "unit", "until", "up", "upon", "us", "use", "usually", "value", "various", 
    "very", "victim", "view", "violence", "visit", "voice", "vote", "wait", "walk", "wall", 
    "want", "war", "watch", "water", "way", "we", "weapon", "wear", "week", "weight", 
    "well", "west", "western", "what", "whatever", "when", "where", "whether", "which", "while", 
    "white", "who", "whole", "whom", "whose", "why", "wide", "wife", "will", "win", 
    "wind", "window", "wish", "with", "within", "without", "woman", "wonder", "word", "work", 
    "worker", "world", "worry", "would", "write", "writer", "wrong", "yard", "yeah", "year", 
    "yes", "yet", "you", "young", "your", "yourself", 
]
